[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# [".config/rofi/themes"]
#     type = "archive"
#     url = "https://github.com/ulises-jeremias/rofi-themes/archive/main.tar.gz"
#     exact = true
#     stripComponents = 2

